### ISSUE TITLE
APK FILES ARE NOT DOWNLODING

### ISSUE THREAD

**Issue by Usman-Click** [HarshAndroid/VideoPlayer#1]
APK files are not downloading, it says this site cannot be reach.

**Comment by HarshAndroid** [comment]
Actually apk downloading is working on my side but if you're still getting this issue then try one of this url: https://doc-0o-ak-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/udtvgt0rstb11i76gga7tj9lf0nk7nn5/1656223800000/16559608812870303168/*/1b955pdRCQAfmRjg5rQxpCM2Y8f16Cz7L?e=download
Or https://drive.google.com/uc?id=1b955pdRCQAfmRjg5rQxpCM2Y8f16Cz7L&export=download

**Comment by Usman-Click** [comment]
Is still not working 

Can u pls send me the zip file to  my mail Uadamuharuna@gmail.com 

Thanks

**Comment by HarshAndroid** [comment]
Hey buddy actually google doesn't allow zip or apk file sharing directly through Gmail nowadays. So I would suggest you to download project & build apk for yourself.

**Comment by Usman-Click** [comment]
Okay thanks

**Comment by Usman-Click** [comment]
It still shows the same thing

Can send the zip file through here (email)

**Comment by HarshAndroid** [comment]
Now you can download apk with project zip.
Located in  /Screen_shots_of_app folder.

Link: https://github.com/HarshAndroid/VideoPlayer/blob/master/Screen_shots_of_app/Video%20Player%20v1.0.5.apk

**Comment by Usman-Click** [comment]
Okay thanks
