### ISSUE TITLE
Video Playing Issue

### ISSUE THREAD

**Issue by AshishYesale7** [HarshAndroid/VideoPlayer#2]
Video is played but but screen is blank no audio , rather than mp4 no other video is played plz fix the issue  Thx in Advance.

**Comment by HarshAndroid** [comment]
Actually buddy I can't do much regarding video playing formats because it is handled by Exoplayer Internally (and the image you share with me (through email) shows that file you're playing is Ep.mvk & I don't think their is such an file format called .mvk , so try changing it to .mkv or .MP4).
