### ISSUE TITLE
New Version Necessory

### ISSUE THREAD

**Issue by StrangeCurious** [HarshAndroid/VideoPlayer#3]
The latest SDK 33 will be appreciated for your video player app.

**Comment by AshishYesale7** [comment]
> The latest SDK 33 will be appreciated for your video player app.

**Comment by HarshAndroid** [comment]
I've Updated the SDK to 33 & Added Android 13 Permission Support too.

**Comment by Bhagsa123** [comment]
Permission dailog not showing in Android 13

**Comment by StrangeCurious** [comment]
Its not able to grant the permission which are required to read the files from internal storage

**Comment by HarshAndroid** [comment]
I've Updated Codes, Now Check & Let me know.

**Comment by StrangeCurious** [comment]
Now, the app asks for the required permission and works well.
