### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by rajpakira24** [HarshAndroid/VideoPlayer#5]
After go all folders and clicking on any folder view the app closed. https://github.com/HarshAndroid/VideoPlayer/assets/58460022/a091edef-49af-410a-9bc7-67ea4fcf1cea

**Comment by HarshAndroid** [comment]
Okay, I will check and try to fix it as soons as possible.

**Comment by HarshAndroid** [comment]
Now you can check & let me know.
